---
AWSTemplateFormatVersion: 2010-09-09
Description: Xplorers Bot
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Description: HTTP API Stage name
    Type: String
  SlackOauthTokenSsmPath:
    Description: Ssm path containing slack oauth token
    Type: String
  SentryDsnSsmPath:
    Description: Ssm path containing sentry dsn
    Type: String
  Environment:
    Description: XplorersBot Environment (dev/test/prod)
    Type: String
  ChatgptApiKeySsmPath:
    Description: Ssm path containing chat gpt api key
    Type: String
  XplorersChatbotSlackChannelIdSsmPath:
    Description: Ssm path containing ID of slack channel where Xplorers interact with the chatbot
    Type: String

Mappings:
  AwsRegionToLayerArnMap:
    ap-southeast-2:
      # AWS Managed lambda layer
      # https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-integration-lambda-extensions.html#:~:text=URL%20is%20used.-,AWS%20Parameters%20and%20Secrets%20Lambda%20Extension%20ARNs,-The%20following%20tables
      LayerArn: arn:aws:lambda:ap-southeast-2:665172237481:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4

Globals:
  Function:
    Runtime: go1.x
    MemorySize: 128
    Timeout: 30
    Environment:
      Variables:
        SENTRY_DSN_SSM_PATH: !Ref SentryDsnSsmPath
        ENVIRONMENT: !Ref Environment
    Layers:
      - !FindInMap [AwsRegionToLayerArnMap, !Ref AWS::Region, LayerArn]

Resources:
  XplorersBotServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: API used for all Xplorers' needs
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: apispec.yaml
      EndpointConfiguration:
          Type: REGIONAL

  XplorersBotGo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda.zip
      Handler: xplorersbot
      Environment:
        Variables:
          SLACK_OAUTH_TOKEN_SSM_PATH: !Ref SlackOauthTokenSsmPath
      Events:
        CallXplorersBotFunction:
          Type: Api
          Properties:
            RestApiId: !Ref XplorersBotServerlessApi
            Method: POST
            Path: /
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SlackOauthTokenSsmPath}
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SentryDsnSsmPath}

  XplorersBotEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref XplorersBotGo
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
      MaximumEventAgeInSeconds: 60

  XplorersBotLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${XplorersBotGo}
      RetentionInDays: 3

  XplorersChatBot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda.zip
      Handler: xplorersChatBot
      Environment:
        Variables:
          CHATGPT_API_KEY_SSM_PATH: !Ref ChatgptApiKeySsmPath
          XPLORERS_CHATBOT_SLACK_CHANNEL_ID_SSM_PATH: !Ref XplorersChatbotSlackChannelIdSsmPath
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SentryDsnSsmPath}
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ChatgptApiKeySsmPath}
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${XplorersChatbotSlackChannelIdSsmPath}
      Events:
        InvokeXplorersChatBot:
          Type: Api
          Properties:
            RestApiId: !Ref XplorersBotServerlessApi
            Method: POST
            Path: /chat

  XplorersChatBotEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref XplorersChatBot
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
      MaximumEventAgeInSeconds: 60

  XplorersChatBotLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${XplorersChatBot}
      RetentionInDays: 3

Outputs:
  XplorersBotServerlessApiUrl:
    Description: URL of Xplorers Bot API endpoint - This URL is invoked by Slack
    Value: !Sub https://${XplorersBotServerlessApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/

  XplorersChatBotServerlessApiUrl:
    Description: URL of Xplorers Chat Bot API endpoint - This URL is invoked by Slack
    Value: !Sub https://${XplorersBotServerlessApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/chat/

  XplorersBotServerlessApiId:
    Description: Api id of ServerlessApi
    Value:
      Ref: XplorersBotServerlessApi
