name: Deploy XplorersBot to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy_xplorers_bot_to_aws:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      API_STAGE: prod
    steps:
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-southeast-2'

    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Deploy XplorersBot!
      run: make deploy-xplorers-bot
