name: Run go unit tests

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Run tests
      run: make test
